version: '3'
services:
  app:
    build: .
    env_file:
      - .env
    environment:
      - APP_DIR=/app
      - QUERY_FILE=query.csv
      - SELENIUM_URL=http://selenium:4444/wd/hub
      - PYTHONUNBUFFERED=1
    volumes:
      - ./query.csv:/app/query.csv:ro
      - ./data:/app/data
      - ./.env:/app/.env:ro
    depends_on:
      selenium:
        condition: service_healthy
    restart: on-failure:3

  selenium:
    build:
      context: .
      dockerfile: selenium.Dockerfile
    ports:
      - "4444:4444"
    shm_size: '2gb'
    environment:
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s