apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
      - name: scraper
        image: your-registry/scraper:latest  # 実際のイメージに置き換えてください
        env:
        - name: SELENIUM_HOST
          value: "selenium-standalone"
        - name: ENVIRONMENT
          value: "production"