apiVersion: v1
kind: Secret
metadata:
  name: scraper-secrets
  namespace: default
type: Opaque
stringData:
  # API設定
  GEMINI_API_KEY: "your-api-key-here"
  API_RATE_LIMIT_SECONDS: "1.0"
  
  # Selenium設定
  SELENIUM_URL: "http://selenium-standalone:4444/wd/hub"
  
  # キャッシュ設定
  CACHE_EXPIRATION_HOURS: "24"
  CACHE_MAX_SIZE: "1000"
  CACHE_FILE_PATH: "/app/cache/cache.json"
  
  # ロギング設定
  LOG_LEVEL: "INFO"